stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app-java:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 172.20.12.139:32076/repository/my-docker-repo/
- name: push
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
