stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app-java:${CICD_EXECUTION_SEQUENCE}
      registry: 172.20.12.139:30002
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_MIRROR: 172.20.12.139:30002
        
- name: push
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
