stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app-java:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34976
- name: push
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
