stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: app-java:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: localhost:30082
    env:
      PLUGIN_INSECURE: "true"
- name: push
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
