apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: java-app
  namespaces: default
spec:
  selector:
    matchLabels: 
      app: java
  progressDeadlineSeconds: 600
  replicas: 1
  template: 
    metadata: 
      labels:
        app: java
    spec:
      containers:
      - name: java-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
