apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ci-cd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  template: 
    metadata: 
    spec:
      containers:
      - name: java-app
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
